version: '2'
services:
    xmanager-app:
        image: xmanager
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://xmanager-mysql:3306/xmanager?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    xmanager-mysql:
        extends:
            file: mysql.yml
            service: xmanager-mysql
